# Generated by Django 5.1.6 on 2025-04-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id_reglement', models.AutoField(primary_key=True, serialize=False)),
                ('num_contrat', models.CharField(max_length=100)),
                ('id_client', models.CharField(max_length=100)),
                ('date_contrat', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('categorie', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_assurance', models.DateField()),
                ('date_reglement', models.DateField()),
                ('montant_reglement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.salle')),
            ],
        ),
    ]
